const dotenv = require("dotenv");
dotenv.config();

const { STRIPE_TEST_SECRET_KEY, STRIPE_PROD_SECRET_KEY, HELLOASSO_CLIENT_ID, HELLOASSO_CLIENT_SECRET, HELLOASSO_API_ENDPOINT, HELLOASSO_ORGANIZATION_SLUG, SUPABASE_URL, SUPABASE_SECRET_KEY } =
  process.env;

export enum TRANSACTION_TYPES {
  SUBSCRIPTION = "subscription",
  DONATION = "donation",
  SALE = "sale",
  PAYOUT = "payout",
  REFUND = "refund",
  FEE = "fee",
  OTHER = "other"
}

module.exports = {
  STRIPE_TEST_SECRET_KEY,
  STRIPE_PROD_SECRET_KEY,
  HELLOASSO_CLIENT_ID,
  HELLOASSO_CLIENT_SECRET,
  HELLOASSO_API_ENDPOINT,
  HELLOASSO_ORGANIZATION_SLUG,
  SUPABASE_URL,
  SUPABASE_SECRET_KEY,
  TRANSACTION_TYPES
};
